name: Hello World PR Comment

on:
  pull_request_review_comment:
    types: [created]

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Check for "hello" in comment
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const body = context.payload.comment.body.toLowerCase();
            if (body.includes('hello')) {
              console.log('Hello, world!');
            }
