name: Hello World PR Comment

on:
  issue_comment:
    types: [created]

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Check for "hello" in comment
        if: contains(github.event.comment.body, 'hello')
        run: echo "Hello, world!"
